# Generated by Django 5.0.6 on 2024-07-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_datasabertas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidades',
            name='icone',
        ),
    ]
